package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPageCount(java.lang.Integer pageCount) {
		set("pageCount", pageCount);
	}
	
	public java.lang.Integer getPageCount() {
		return getInt("pageCount");
	}

	public void setMoney(java.lang.Double money) {
		set("money", money);
	}
	
	public java.lang.Double getMoney() {
		return getDouble("money");
	}

}
