package com.demo.common.model;

import com.demo.common.model.base.BaseBaominghaoXianquma;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaominghaoXianquma extends BaseBaominghaoXianquma<BaominghaoXianquma> {
	
}
